update root_letter set core_meaning = 'فعل: لانا' where root_letter_text = 'ه ا ت';
update root_letter set core_meaning = 'فعل: نیچے جانا' where root_letter_text = 'ه ب ط';
update root_letter set core_meaning = 'اسم: دھول' where root_letter_text = 'ه ب و';
update root_letter set core_meaning = 'فعل: نیند سے اٹھنا' where root_letter_text = 'ه ج د';
update root_letter set core_meaning = 'ہجرت، اجتناب' where root_letter_text = 'ه ج ر';
update root_letter set core_meaning = 'فعل: سونا' where root_letter_text = 'ه ج ع';
update root_letter set core_meaning = 'اسم: تباہی' where root_letter_text = 'ه د د';
update root_letter set core_meaning = 'فعل: گرا دینا' where root_letter_text = 'ه د م';
update root_letter set core_meaning = 'اسم: ہدہد' where root_letter_text = 'ه د ه د';
update root_letter set core_meaning = 'رہنمائ' where root_letter_text = 'ه د ى';
update root_letter set core_meaning = 'اسم: اڑان' where root_letter_text = 'ه ر ب';
update root_letter set core_meaning = 'فعل: جلدی کرنا' where root_letter_text = 'ه ر ع';
update root_letter set core_meaning = 'تمسخر' where root_letter_text = 'ه ز ا';
update root_letter set core_meaning = 'فعل: ہلانا' where root_letter_text = 'ه ز ز';
update root_letter set core_meaning = 'اسم: تفریح' where root_letter_text = 'ه ز ل';
update root_letter set core_meaning = 'فعل: شکست' where root_letter_text = 'ه ز م';
update root_letter set core_meaning = 'فعل: پتے جھاڑنا' where root_letter_text = 'ه ش ش';
update root_letter set core_meaning = 'اسم: خشک ٹہنیاں' where root_letter_text = 'ه ش م';
update root_letter set core_meaning = 'اسم: محرومی' where root_letter_text = 'ه ض م';
update root_letter set core_meaning = 'بھاگ کر آگے نکلنا' where root_letter_text = 'ه ط ع';
update root_letter set core_meaning = 'اسم: پریشان' where root_letter_text = 'ه ل ع';
update root_letter set core_meaning = 'ہلاکت، تباہی' where root_letter_text = 'ه ل ك';
update root_letter set core_meaning = 'فعل: وقف کرنا ؛ اسم: چاند' where root_letter_text = 'ه ل ل';
update root_letter set core_meaning = 'بنجر' where root_letter_text = 'ه م د';
update root_letter set core_meaning = 'برسنا' where root_letter_text = 'ه م ر';
update root_letter set core_meaning = 'اسم: تجویز، بدگوئ' where root_letter_text = 'ه م ز';
update root_letter set core_meaning = 'اسم: سرگوشی' where root_letter_text = 'ه م س';
update root_letter set core_meaning = 'فعل: ارادہ، پریشانی' where root_letter_text = 'ه م م';
update root_letter set core_meaning = 'نگہبان' where root_letter_text = 'ه م ن';
update root_letter set core_meaning = 'اطمینان' where root_letter_text = 'ه ن ا';
update root_letter set core_meaning = 'یہودی، ھود علیہ السلام' where root_letter_text = 'ه و د';
update root_letter set core_meaning = 'گرنا' where root_letter_text = 'ه و ر';
update root_letter set core_meaning = 'توہین' where root_letter_text = 'ه و ن';
update root_letter set core_meaning = 'خواہش' where root_letter_text = 'ه و ى';
update root_letter set core_meaning = 'فعل: آسانی پیدا کرنا ؛ اسم: مشابہت' where root_letter_text = 'ه ى ا';
update root_letter set core_meaning = 'کر جاؤ' where root_letter_text = 'ه ى ت';
update root_letter set core_meaning = 'فعل: مرجھانا' where root_letter_text = 'ه ى ج';
update root_letter set core_meaning = 'برسنا' where root_letter_text = 'ه ى ل';
update root_letter set core_meaning = 'فعل: گھومنا ؛ اسم: پیاسا اونٹ' where root_letter_text = 'ه ى م';
COMMIT;
update root_letter set core_meaning = 'زندہ دفن کر دی جانے والی نومولود بچی' where root_letter_text = 'و ا د';
update root_letter set core_meaning = 'اسم: فرار' where root_letter_text = 'و ا ل';
update root_letter set core_meaning = 'اسم: اون' where root_letter_text = 'و ب ر';
update root_letter set core_meaning = 'فعل: تباہ کرنا ؛ اسم: رکاوٹ' where root_letter_text = 'و ب ق';
update root_letter set core_meaning = 'اسم: برا نتیچہ، بارش' where root_letter_text = 'و ب ل';
update root_letter set core_meaning = 'اسم: میخ، کیل' where root_letter_text = 'و ت د';
update root_letter set core_meaning = 'فعل: محروم کرنا ؛ اسم: طاق، وراثت' where root_letter_text = 'و ت ر';
update root_letter set core_meaning = 'اسم: ابھرانہ شریان' where root_letter_text = 'و ت ن';
update root_letter set core_meaning = 'فعل: باندھنا ؛ اسم: وعدہ' where root_letter_text = 'و ث ق';
update root_letter set core_meaning = 'اسم: مجسمہ' where root_letter_text = 'و ث ن';
update root_letter set core_meaning = 'فعل: نیچے ہونا' where root_letter_text = 'و ج ب';
update root_letter set core_meaning = 'فعل: ڈھونڈنا ؛ اسم: وسائل' where root_letter_text = 'و ج د';
update root_letter set core_meaning = 'فعل: محسوس کرنا' where root_letter_text = 'و ج س';
update root_letter set core_meaning = 'فعل: مہم جوئ' where root_letter_text = 'و ج ف';
update root_letter set core_meaning = 'خوف' where root_letter_text = 'و ج ل';
update root_letter set core_meaning = 'فعل: مڑنا ؛ اسم: چہرہ، سمت، عزت' where root_letter_text = 'و ج ه';
update root_letter set core_meaning = 'واحد' where root_letter_text = 'و ح د';
update root_letter set core_meaning = 'اسم: جنگلی جانور' where root_letter_text = 'و ح ش';
update root_letter set core_meaning = 'وحی' where root_letter_text = 'و ح ى';
update root_letter set core_meaning = 'محبت، خواہش' where root_letter_text = 'و د د';
update root_letter set core_meaning = 'فعل: نظرانداز کرنا' where root_letter_text = 'و د ع';
update root_letter set core_meaning = 'اسم: بارش' where root_letter_text = 'و د ق';
update root_letter set core_meaning = 'اسم: وادی' where root_letter_text = 'و د ى';
update root_letter set core_meaning = 'فعل: چھوڑ دینا' where root_letter_text = 'و ذ ر';
update root_letter set core_meaning = 'وراثت' where root_letter_text = 'و ر ث';
update root_letter set core_meaning = 'فعل: آنا، رہنمائ ؛ اسم: پیاس، گلاب، ورید' where root_letter_text = 'و ر د';
update root_letter set core_meaning = 'اسم: پتے' where root_letter_text = 'و ر ق';
update root_letter set core_meaning = 'فعل: چھپانا، جلانا ؛ اسم: پیچھے' where root_letter_text = 'و ر ى';
update root_letter set core_meaning = 'فعل: اٹھانا ؛ اسم: بوجھ، وزیر' where root_letter_text = 'و ز ر';
update root_letter set core_meaning = 'فعل: قطار بنانا، قوت دینا' where root_letter_text = 'و ز ع';
update root_letter set core_meaning = 'فعل: وزن کرنا ؛ اسم: ترازو، وزن' where root_letter_text = 'و ز ن';
update root_letter set core_meaning = 'مرکز، وسط' where root_letter_text = 'و س ط';
update root_letter set core_meaning = 'فعل: احاطہ کرنا ؛ اسم: وسعت، وسائل' where root_letter_text = 'و س ع';
update root_letter set core_meaning = 'فعل: احاطہ کرنا، پورا' where root_letter_text = 'و س ق';
update root_letter set core_meaning = 'اسم: وسائل' where root_letter_text = 'و س ل';
update root_letter set core_meaning = 'فعل: داغنا، تمیز کرنا' where root_letter_text = 'و س م';
update root_letter set core_meaning = 'اسم: نیند' where root_letter_text = 'و س ن';
update root_letter set core_meaning = 'سرگوشی' where root_letter_text = 'و س و س';
update root_letter set core_meaning = 'اسم: داغ' where root_letter_text = 'و ش ى';
update root_letter set core_meaning = 'مستقل' where root_letter_text = 'و ص ب';
update root_letter set core_meaning = 'داخلہ، اوپر سے بند کرنا' where root_letter_text = 'و ص د';
update root_letter set core_meaning = 'اوصاف' where root_letter_text = 'و ص ف';
update root_letter set core_meaning = 'فعل: مل جانا، پہنچ جانا ؛ اسم: اونٹنی' where root_letter_text = 'و ص ل';
update root_letter set core_meaning = 'فعل: بنانا، جوڑنا، ہدایت ؛ اسم: وصیت' where root_letter_text = 'و ص ى';
update root_letter set core_meaning = 'فعل: وضع کرنا، بچہ جننا؛ اسم: جگہیں' where root_letter_text = 'و ض ع';
update root_letter set core_meaning = 'آراستہ' where root_letter_text = 'و ض ن';
update root_letter set core_meaning = 'فعل: پیشقدمی، روندنا ؛ اسم: سیڑھی، موثر' where root_letter_text = 'و ط ا';
update root_letter set core_meaning = 'اسم: ضرورت' where root_letter_text = 'و ط ر';
update root_letter set core_meaning = 'اسم: علاقہ' where root_letter_text = 'و ط ن';
update root_letter set core_meaning = 'وعدہ، تعین، دھمکی' where root_letter_text = 'و ع د';
update root_letter set core_meaning = 'وعظ، ہدایت' where root_letter_text = 'و ع ظ';
update root_letter set core_meaning = 'فعل: رکھنا، آگاہ ہونا ؛ اسم: تھیلا' where root_letter_text = 'و ع ى';
update root_letter set core_meaning = 'وفد' where root_letter_text = 'و ف د';
update root_letter set core_meaning = 'کافی' where root_letter_text = 'و ف ر';
update root_letter set core_meaning = 'جلدی' where root_letter_text = 'و ف ض';
update root_letter set core_meaning = 'فعل: سمجھوتا' where root_letter_text = 'و ف ق';
update root_letter set core_meaning = 'فعل: مکمل ادایگی، فوتیدگی' where root_letter_text = 'و ف ى';
update root_letter set core_meaning = 'فعل: پھیلنا' where root_letter_text = 'و ق ب';
update root_letter set core_meaning = 'وقت' where root_letter_text = 'و ق ت';
update root_letter set core_meaning = 'فعل: جلانا ؛ اسم: ایندھن' where root_letter_text = 'و ق د';
update root_letter set core_meaning = 'چوٹ سے ہلاکت' where root_letter_text = 'و ق ذ';
update root_letter set core_meaning = 'فعل: توقیر ؛ اسم: وقار، بہرا، بوجھ' where root_letter_text = 'و ق ر';
update root_letter set core_meaning = 'فعل: واقع ہونا/کرنا ؛ اسم: وقوعہ' where root_letter_text = 'و ق ع';
update root_letter set core_meaning = 'توقف' where root_letter_text = 'و ق ف';
update root_letter set core_meaning = 'فعل: بچنا، ڈرنا ؛ اسم: راستبازی' where root_letter_text = 'و ق ى';
update root_letter set core_meaning = 'فعل: ٹیک لگانا' where root_letter_text = 'و ك ا';
update root_letter set core_meaning = 'توثیق' where root_letter_text = 'و ك د';
update root_letter set core_meaning = 'فعل: ضرب لگانا' where root_letter_text = 'و ك ز';
update root_letter set core_meaning = 'فعل: بھروسہ ؛ اسم: محافظ، منتظم' where root_letter_text = 'و ك ل';
update root_letter set core_meaning = 'فعل: گھسنا، داخل ہونا' where root_letter_text = 'و ل ج';
update root_letter set core_meaning = 'فعل: تولید ؛ اسم: والدین، اولاد' where root_letter_text = 'و ل د';
update root_letter set core_meaning = 'فعل: پیٹھ موڑنا ؛ اسم: ساتھی، وارث، محافظ' where root_letter_text = 'و ل ى';
update root_letter set core_meaning = 'فعل: ڈھیل' where root_letter_text = 'و ن ى';
update root_letter set core_meaning = 'عنایت' where root_letter_text = 'و ه ب';
update root_letter set core_meaning = 'جلنا' where root_letter_text = 'و ه ج';
update root_letter set core_meaning = 'کمزوری' where root_letter_text = 'و ه ن';
update root_letter set core_meaning = 'کمزور' where root_letter_text = 'و ه ى';
COMMIT;
update root_letter set core_meaning = 'مایوسی' where root_letter_text = 'ى ا س';
update root_letter set core_meaning = 'خشک' where root_letter_text = 'ى ب س';
update root_letter set core_meaning = 'یتیم' where root_letter_text = 'ى ت م';
update root_letter set core_meaning = 'اسم: ہاتھ' where root_letter_text = 'ى د ى';
update root_letter set core_meaning = 'فعل: آسان کرنا ؛ اسم: آسانی، جوا' where root_letter_text = 'ى س ر';
update root_letter set core_meaning = 'اسم: جاگنا' where root_letter_text = 'ى ق ظ';
update root_letter set core_meaning = 'یقین' where root_letter_text = 'ى ق ن';
update root_letter set core_meaning = 'فعل: تیمم ؛ اسم: سمندر، دریا' where root_letter_text = 'ى م م';
update root_letter set core_meaning = 'اسم: دایاں، حلف' where root_letter_text = 'ى م ن';
update root_letter set core_meaning = 'اسم: پکا ہوا' where root_letter_text = 'ى ن ع';
update root_letter set core_meaning = 'یوم' where root_letter_text = 'ى و م';
COMMIT;
