INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (1, 'اَلْفَاتِحَة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (2, 'ألْبَقَرَة', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (3, 'آلِ عِمْرَان',2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (4, 'ألْنِّسَاء', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (5, 'ألْمَاْئِدَة', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (6, 'اَلْأَنْعَام', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (7, 'اَلْأَعْرَاف', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (8, 'اَلْأَنْفَال', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (9, 'اَلتَّؤبَة', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (10, 'يُونُس', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (11, 'هُود',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (12, 'يُوسُف', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (13, 'ألرَّعْد', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (14, 'إِبْرَاهِيم', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (15, 'ألْحِجْر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (16, 'ألنَّحْل', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (17, 'ألْإسْرَاء', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (18, 'ألْكَهْف', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (19, 'مَرْيَم', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (20, 'طه', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (21, 'ألْأَنْبِيَاء', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (22, 'ألْحَجّ', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (23, 'ألْمُؤْمِنُون',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (24, 'ألنُّور', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (25, 'ألْفُرْقَان', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (26, 'ألشُّعَرَاء', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (27, 'ألنَّمْل', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (28, 'ألْقَصَص', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (29, 'ألْعَنْكَبُوت', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (30, 'ألرُّوم', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (31, 'لُقْمَان',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (32, 'ألسَّجْدَة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (33, 'ألْأَحْزَاب', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (34, 'سَبَأ', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (35, 'فَاطِِر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (36, 'يس', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (37, 'ألصَّافَّات', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (38, 'ص', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (39, 'ألزُّمَر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (40, 'غَافِر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (41, 'فصِّلَت', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (42, 'ألشُّورى', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (43, 'ألْزُّخْرُف',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (44, 'ألدُّخَان', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (45, 'ألْجَاثِيَة', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (46, 'ألْأَحْقَاف', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (47, 'مُحَمَّد', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (48, 'ألْفَتْح', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (49, 'ألْحُجُرَات', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (50, 'ق', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (51, 'ألذَّارِيَات',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (52, 'ألطُّور', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (53, 'ألنَّجْم', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (54, 'ألْقَمَر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (55, 'ألرَّحْمَن', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (56, 'ألْوَاقِعَة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (57, 'ألْحَدِيد', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (58, 'ألْمُجَادِلَة', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (59, 'ألْحَشْر', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (60, 'ألْمُمْتَحَنَة', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (61, 'ألصّفّ', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (62, 'ألْجُمُعَة', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (63, 'ألْمُنَافِقُون',2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (64, 'ألتَّغَابُن', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (65, 'ألطَّلَاق', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (66, 'ألتَّحْرِيم', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (67, 'ألْمُلْك', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (68, 'ألْقَلَم', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (69, 'ألْحَاقَّة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (70, 'ألْمَعَارِج', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (71, 'نُوح',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (72, 'ألْجِنّ', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (73, 'ألْمُزَّمِّل', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (74, 'ألْمُدَّثِّر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (75, 'ألْقِيَامَة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (76, 'ألْإِنْسَان', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (77, 'ألْمُرْسَلَات', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (78, 'ألنَّبَأ', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (79, 'ألنَّازِعَات', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (80, 'عَبَسَ', 1);
--
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (81, 'ألتَّكْوِير', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (82, 'ألْإَنْفِطَار', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (83, 'ألْمُطَفِّفِين',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (84, 'ألْإِنْشِقَاق', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (85, 'ألْبُرُوج', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (86, 'ألطَّارِق', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (87, 'ألْأَعْلَى', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (88, 'ألْغَاشِيَة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (89, 'ألْفَجْر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (90, 'ألْبَلَد', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (91, 'ألْشَّمْس',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (92, 'أللِّيْل', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (93, 'ألْضُّحَي', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (94, 'ألشَّرْح', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (95, 'ألتِّين', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (96, 'ألْعَلَق', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (97, 'ألْقَدْر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (98, 'ألْبَيِّنَة', 2);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (99, 'ألزَّلْزَلَة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (100, 'ألْعَادِيَات', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (101, 'ألْقَارِعَة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (102, 'ألتَّكَاثُر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (103, 'ألْعَصْر',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (104, 'ألْهُمَزَة', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (105, 'ألْفِيل', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (106, 'قُرَيْش', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (107, 'ألْمَاعُون', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (108, 'ألْكُوْثَر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (109, 'ألْكَافِرُن', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (110, 'ألنَّصْر', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (111, 'ألْمَسَد',1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (112, 'ألْإِخْلَاس', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (113, 'ألْفَلَق', 1);
INSERT INTO soorah (soorah_seq_no, soorah_name, revelation_location_id) VALUES (114, 'ألنَّاس', 1);

COMMIT;