--'ج'
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جِبْرِيل', root_letter_id FROM root_letter WHERE root_letter_text = 'ج';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَالُوت', root_letter_id FROM root_letter WHERE root_letter_text = 'ج';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَهَنَّم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'تَجْأَرُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ا ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'تَجْأَرُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ا ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'يَجْأَرُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ا ر';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'الْجُبَّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ب';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'الْجِبْتِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ت';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَبَّار', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَبَّارًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَبَّارِينَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ر';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَبَلٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جِبَال', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جِبِلَّا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'الجِبِلَّةَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ل';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'لِلْجَبِينِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ن';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جِبَاهُهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ه';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'يُجْبَى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'اجْتَبَاكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'اجْتَبَاهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'اجْتَبَيْتَهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'اجْتَبَيْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'اجْتَبَيْنَاهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'يَجْتَبِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'يَجْتَبِيكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'الْجَوَابِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ب ى';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'اجْتُثَّتْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ت ث';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَاثِمِينَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ث م';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَاثِيَةً', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ث و';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جثِيَّا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ث و';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَحَدُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ح د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'يَجْحَدُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ح د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'يَجْحَدُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ح د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَحِيم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ح م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَحِيمًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ح م';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'الْأَجْدَاثِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ث';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَدُّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَدِيدٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جدِيدًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جُدَدٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'أَجْدَرُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'الْجِدَارُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جدَارًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جُدُرٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ر';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'حَادَلْتُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'حَادَلْتَنا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَادَلُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جَادَلُوكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'تُجَادِلْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'تُجَادِلُكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'تُجَادِلُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'اتُجَادِلُونَنِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'يُجَادِلُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'يُجَادِلُنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'لِيُجَادِلُوكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'يُجَادِلُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'يُجَادِلُونَكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'جَادِلْهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'جَدَلًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'جِدَالَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'جِدَالَنا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج د ل';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'مَجْذُوذٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ذ ذ';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جُذَانًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ذ ذ';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جِذْعِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ذ ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جُذُوعِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ذ ع';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَذْوَةٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ذ و';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَرَحْتُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'ٱجْتَرَحُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'الْجُرُوحَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'الْجَوَارِح', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ح';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَرَادَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'يَجُرُّهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ر';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'الْجُرُزِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ز';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جُرُزًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ز';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'يَتَجَرَّعُهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ع';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جُرُفٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ف';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'يَجْرِمَنَّكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'أَجْرَمْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'أَجْرَمُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'تُجْرِمُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'إِجْرَامِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'المُجْرِمُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'مُجْرِمًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'مُجْرِمُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'مُجْرِمِينَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'مُجْرِمِيهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'جَرَمَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر م';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَرَيْنَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'تَجْرِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'تَجْرِيَانِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'يَجْرِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'جَارِيَة', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'فَالْجَارِيَاتِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'الْجَوَارِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'مَجْرىهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ر ى';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جُزْءٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جُزْءًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ا';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَزِعْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَزُوعًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ع';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَزَاهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَزَيْتُهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَزَيْنَاهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'تَجْزِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'نَجْزِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'لَنَجْزِيَنَّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'لَنَجْزِيَنَّهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'نَجْزِيهِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'يَجْزِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'لِيَجْزِيَكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'يَجْزِيُهمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'تُجْزَى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'تُجْزَوْنَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'يُجْزَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'يُجْزَى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'يُجْزَاهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'يُجْزَوْنَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'نُجَازِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'جَازٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'جَزَاءُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 21, 'جَزَاؤُكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 22, 'جَزَاؤُهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 23, 'جَزَاؤُهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 24, 'الْجِزْيَةَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ز ى';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَسَدًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج س د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'تَجَسَّسُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج س س';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'الجِسْمِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج س م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'أَجْسَامُهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج س م';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَعَلَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَعَلَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَعَلْتُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جَعَلْتُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'جَعَلَتْهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'جَعَلَكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'جَعَلْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'جَعَلْنَاكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'جَعَلْنَاكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'جَعَلْنَاهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'جَعَلْنَاهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'جَعَلْنَاهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'فَجَعَلْنَاهُنَّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'جَعَلَنِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'جَعَلَهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'جَعَلَهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'جَعَلَهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'جَعَلُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'أَجْعَلْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'لَأَجْعَلَنَّكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 21, 'تَجْعَلْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 22, 'تَجْعَلْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 23, 'تَجْعَلْنِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 24, 'تَجْعَلُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 25, 'تَجْعَلُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 26, 'تَجْعَلُونَهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 27, 'نَجْعَلُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 28, 'وَلِنَحْعَلَكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 29, 'وَلِنَجْعَلَهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 30, 'نَجْعَلُهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 31, 'نَجْعَلْهُمَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 32, 'نَجْعَلَهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 33, 'يَجْعَل', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 34, 'وَيَجْعَلُكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 35, 'يَجْعَلْنِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 36, 'يَجْعَلهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 37, 'يَجْعَلُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 38, 'يَجْعَلُوهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 39, 'اجْعَلْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 40, 'اجْعَلْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 41, 'اجْعَلْنِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 42, 'واجْعَلْهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 43, 'اجْعَلُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 44, 'جُعِلَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 45, 'جَاعِلٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 46, 'جَاعِلُكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 47, 'لَجَعِلُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 48, 'وَجَاعِلُوهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ع ل';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جُفَاء', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ف ا';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جِفَانٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ف ن';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'تَتَجَافَى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ف و';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'أجْلِب', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَلَابِيبِهِنَّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل ب';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'فٱجْلِدوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'فٱجْلِدوهم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَلْدَة', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جُلُود', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'جُلُودًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'جُلُودُكم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'جُلُودُهُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'المَجَالِسِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل س';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'الْجَلَال', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل ل';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَلَّاهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل و';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'يُجَلِّيها', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل و';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'تَجَلَّى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل و';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'الْجَلَاءَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ل و';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'يَجْمَحُون', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ح';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَامِدةً', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَمَعَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَمَعْنَاكُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جمَعْنَاهم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جَمَعَهُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'جَمَعُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'تَجْمَعُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'نَجْمَع', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'يَجْمَع', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'يَجْمَعُكم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'لَيَجْمَعَنَّكم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'يَجْمَعُون', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'جُمِع', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'أجْمَعُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'أَجْمِعُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'اجْتَمَعت', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'اجْتَمَعُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'الْجَمْع', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'جَمْعًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'جَمْعُكُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'جَمْعَهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 21, 'جَمْعِهِم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 22, 'الجَمْعَانِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 23, 'جَامع', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 24, 'مَجْمَع', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 25, 'مَجْمُوعٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 26, 'لَمَجْمُوعون', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 27, 'مُجْتَمِعُون', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 28, 'جَمِيعٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 29, 'جَمِيعًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 30, 'أَجْمَعُون', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 31, 'أَجْمَعِين', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 32, 'الجُمُعَة', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ع';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَمَال', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَمِيل', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَمِيلًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جِمَالَة', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'الجَمَل', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'جُمْلَة', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م ل';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَمَّا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج م م';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'اجْنُبْنِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'سَيُجَنَّبُهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'يَتَجَنَّبُهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'اجْتَنَبُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'تَجْتَنِبُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'يَجْتَنِبُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'اجْتَنِبُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'فاجْتَنِبُوه', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'جَنْب', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'لجَنْبِهِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'جُنُوبِكُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'جُنُوبُهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'جُنُوبهم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'جُنُب', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'جُنُبًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'جَانِب', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'بِجَانِبِه', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ب';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَنَحُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'فٱجْنَحْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَنَاح', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جَنَاحك', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'بِجَنَاحَيْهِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'أَجْنِحَةٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ح';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'جُنَاح', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ح';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جُنْد', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جُنْدًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جُنْدَنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جُنُود', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'جُنُودًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'جُنُوده', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'جُنُودَهُمَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَنَفًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ف';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'مُتَجَانِفِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ف';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَنَّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَانّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'الجِنّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جِنَّة', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'مَجْنُون', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'جَنَّة', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'جَنَّتك', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'جَنَّتَهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'جَنَّتِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'جَنَّتانِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'جَنَّتَيْنِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'بجَنَّتَيْهِم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'جَنَّاتٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'جُنَّةً', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'أَجِنَّةٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ن';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'وَجَنَى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ى';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَنِيَّا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ن ى';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَاهَدَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَاهَدَاكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَاهَدُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'تُجَاهِدُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'يُجَاهِدُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'يُجَاهِدُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'يُجَاهِدُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'جَاهِدِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'جَاهِدْهُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'جَاهِدُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'جَهْدَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'جُهْدَهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'جِهَادٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'جَهَادًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'جِهَادِهِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'الْمُجَاهِدُون', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'الْمُجَاهِدِينَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَهَرَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'تَجْهَرْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'تَجْهَرُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'ٱجْهَرُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'جَهْر', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'جَهْرًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'جَهْرَكُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'جَهْرَةً', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'جِهَارًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ر';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَهَّزَهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ز';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'بِجَهَازِهِم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ز';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'تَجْهلُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'يَجْهَلُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'الجَاهِلُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جَاهِلُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'الْجَاهلِين', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'جَهُولًا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'بِجَهَالَةٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'الْجَاهِلِيَّةِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ه ل';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَابُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'أَجَبْتُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'أُجِيبُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'نُجِبْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'يُجِبْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'يُجِيبُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'أَجِيبُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'أُجِبْتُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'أُجِيبَتْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'اسْتَجَابَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'اسْتَجَابُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'فٱسْتَجَبْتُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'فاسْتَجَبْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'أَسْتَجِبْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'تَسْتَجِيبُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'يَستَجِيب', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'يَسْتَجِيبُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'يَسْتَجِيبُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'ٱسْتَجِيبُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'ٱسْتُجِيبَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 21, 'جَوَابَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 22, 'مُجِيبٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 23, 'الْمُجِيبُونَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ب';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'الْجُودِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و د';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'الْجِيَادُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و د';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'يُجَاوِرُونَكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'وَيُجِرْكُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'يُجِيرُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'يُجِيرَنِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'فَأَجِرْهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'يُجَارُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'اسْتَجَارَكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'جَار', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'جَاىِٔرٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'مُتَجَاوِرَاتٌ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ر';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَاوَزَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ز';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَاوَزْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ز';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَاوَزَهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ز';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'نَتَجَاوَزُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ز';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'فَجَاسُوا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و س';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'تَجُوعَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ع';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جُوعٍ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ع';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَوْفِهِ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و ف';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَوّ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج و و';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَاءَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جَاءَتْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'جَاءَتْك', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'جَاءَتْكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'جَاءَتْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'جَاءَتْهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'جَاءَتْهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'جَاءَتْهُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'جَاءَكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'جَاءَكُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'جَاءَنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'جَاءَنِى', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'جَاءَهُ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'جَاءَهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'جَاءَهُم', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'جَاءُو', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'جاءُوكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'جَاءُوكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'جَاءُوهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'فَجاءُوهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 21, 'جِئْت', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 22, 'جِئْتُكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 23, 'جِئْتُكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 24, 'جِئْتُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 25, 'جِئْتُمُونَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 26, 'جِئْتَنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 27, 'جِئْتَهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 28, 'جِئْنَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 29, 'جِئْنَاكَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 30, 'جِئْنَاكُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 31, 'جِئَنَاهُمْ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 32, 'جِىءَ', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 33, 'فَأَجَاءَهَا', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ا';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جَيْبِك', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ب';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'جُيُوبِهِن', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى ب';
COMMIT;
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'جِيدِها', root_letter_id FROM root_letter WHERE root_letter_text = 'ج ى د';
COMMIT;
--
