--ظ ع ن
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'ظَعْنِكُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ع ن';
COMMIT;
--ظ ف ر
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'أَظْفَرَكُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ف ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'ظُفُرٍ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ف ر';
COMMIT;
--ظ ل ل
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'ظَلَّ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'ظَلَّتْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'ظَلْتَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'فَظَلْتُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'ظَلُّوا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'فَنَظَلُّ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'فَيَظْلَلْنَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'وَظَلَّلْنَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'الظِّل', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'ظِلًّا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'ظِلُّهَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'ظِلَالٍ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'ظِلَالًا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'ظِلَالُهُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'ظِلَالُهَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'ظِلَالُهُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'ظُلَّة', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'ظُلَل', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'ظَلِيلٍ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'ظَلِيلًا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل ل';
COMMIT;
--ظ ل م
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'ظَلَمَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'ظَلَمَتْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'ظَلَمْتُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'ظَلَمْتُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'ظَلَمَكَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'ظَلَمْنَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'ظَلَمْنَاهُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'ظَلَمَهُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'ظَلَمُوا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'ظَلَمُونَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'تَظْلِمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'تَظلِمُوا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'تَظْلِمُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'يَظْلِم', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'لِيَظْلِمَهُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'يَظْلِمُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'ظُلِمَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'ظُلِمُوا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'تُظْلَمُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'تُظْلَمُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 21, 'يُظْلَمُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 22, 'ظُلْم', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 23, 'ظُلْمًا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 24, 'ظُلْمِهِ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 25, 'ظُلْمِهِمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 26, 'ظَالِم', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 27, 'ظَالِمَة', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 28, 'ظَالِمُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 29, 'ظَالِمِى', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 30, 'ظَالِمِينَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 31, 'أَظْلَم', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 32, 'ظَلُومٌ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 33, 'ظَلُومًا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 34, 'ظَلَّامٍ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 35, 'مَظْلُومًا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 36, 'مُظْلِمًا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 37, 'مُظْلِمُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 38, 'ظُلُمَات', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ل م';
COMMIT;
--ظ م ا
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'تَظْمَؤُا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ م ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'ظَمَاٌ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ م ا';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'الظَّمْآنُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ م ا';
COMMIT;
--ظ ن ن
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'ظَنَّ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'ظَنَّا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'ظَنَنْتُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'ظَنَنْتُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'ظَنَنَّا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'ظَنُّوا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'أَظُنُّ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'لَأَظُنُّكَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'لَأَظُنُّهُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'تَظنُّ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'تَظُنُّونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'نَظُنُّ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'نَظُنُّكَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'نَظُنُّكُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'يَظُنُّ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'يَظُنُّونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'الظَّن', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'ظَنُّكُم', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'ظَنَّهُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'الظُّنُونَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 21, 'الظَّانِّينَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ن ن';
COMMIT;
--ظ ه ر
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 1, 'ظَهَرَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 2, 'يَظْهَرُوا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 3, 'يَظْهَرُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 4, 'يَظْهَرُوهُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 5, 'ظَاهَرُوا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 6, 'ظَاهَرُوهُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 7, 'تُظَاهِرُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 8, 'يُظَاهِرُوا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 9, 'يُظَاهِرُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 10, 'أَظْهَرَهُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 11, 'تُظْهِرُون', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 12, 'يُظْهِر', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 13, 'لِيُظْهِرَهُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 14, 'تَظَاهَرَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 15, 'تَظَاهَرُونَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 16, 'ظَهْرَكَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 17, 'ظَهْرِهِ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 18, 'ظَهْرِهَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 19, 'ظُهُورِكُمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 20, 'ظُهُورِهِ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 21, 'ظُهُورهَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 22, 'ظُهُورهمْ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 23, 'ظُهُورُهُمَا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 24, 'ظَاهِر', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 25, 'ظَاهِرًا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 26, 'ظَاهِرَةً', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 27, 'ظَاهِرُهُ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 28, 'ظَاهِرِينَ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 29, 'ظَهِير', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 30, 'ظَهِيرًا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 31, 'الظَّهِيرَةِ', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
INSERT INTO kalimaat (kalimah_seq_no, kalimah_text, root_letter_id ) SELECT 32, 'ظِهْرِيًّا', root_letter_id FROM root_letter WHERE root_letter_text ='ظ ه ر';
COMMIT;
