# Generated by Django 5.0.6 on 2024-07-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArabicAlphabet',
            fields=[
                ('arabic_alphabet_id', models.FloatField(primary_key=True, serialize=False)),
                ('alphabet_text', models.CharField(max_length=5)),
                ('create_user', models.CharField(max_length=30)),
                ('create_date', models.DateField()),
                ('update_user', models.CharField(blank=True, max_length=30, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arabic_alphabet',
                'ordering': ['alphabet_text'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ayat',
            fields=[
                ('ayat_id', models.FloatField(primary_key=True, serialize=False)),
                ('ayat_seq_no', models.FloatField()),
                ('ayat_text', models.CharField(max_length=2500)),
                ('translation_urdu', models.CharField(blank=True, max_length=2500, null=True)),
                ('translation_english', models.CharField(blank=True, max_length=2500, null=True)),
                ('create_date', models.DateField()),
                ('create_user', models.CharField(max_length=40)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'ayat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AyatDetailsByRoot',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('kalimah_seq_no', models.FloatField(blank=True, null=True)),
                ('kalimah_text', models.CharField(max_length=100)),
                ('root_letter_id', models.FloatField(blank=True, null=True)),
                ('soorah_seq_no', models.FloatField()),
                ('soorah_name', models.CharField(max_length=80)),
                ('ayat_seq_no', models.FloatField()),
                ('ayat_text', models.CharField(max_length=2500)),
                ('translation_urdu', models.CharField(blank=True, max_length=2500, null=True)),
                ('revelation_location_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ayat_details_by_root',
                'ordering': ['kalimah_seq_no', 'kalimah_text', 'soorah_seq_no', 'ayat_seq_no'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kalimaat',
            fields=[
                ('kalimaat_id', models.FloatField(primary_key=True, serialize=False)),
                ('kalimah_seq_no', models.FloatField(blank=True, null=True)),
                ('kalimah_text', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
                ('create_user', models.CharField(max_length=40)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'kalimaat',
                'ordering': ['kalimah_text'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KalimaatAyatXref',
            fields=[
                ('kalimaat_ayat_xref_id', models.FloatField(primary_key=True, serialize=False)),
                ('create_user', models.CharField(max_length=30)),
                ('create_date', models.DateField()),
                ('update_user', models.CharField(blank=True, max_length=30, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kalimaat_ayat_xref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhwKalimah',
            fields=[
                ('nhw_kalimah_id', models.FloatField(primary_key=True, serialize=False)),
                ('nhw_kalimah_text', models.CharField(max_length=10, unique=True)),
                ('create_date', models.DateField()),
                ('create_user', models.CharField(max_length=40)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'nhw_kalimah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhwKalimahSubtype',
            fields=[
                ('nhw_kalimah_subtype_id', models.FloatField(primary_key=True, serialize=False)),
                ('nhw_kalimah_subtype_text', models.CharField(max_length=10, unique=True)),
                ('create_date', models.DateField()),
                ('create_user', models.CharField(max_length=40)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'nhw_kalimah_subtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NhwKalimahType',
            fields=[
                ('nhw_kalimah_type_id', models.FloatField(primary_key=True, serialize=False)),
                ('nhw_kalimah_type_text', models.CharField(max_length=10, unique=True)),
                ('create_date', models.DateField()),
                ('create_user', models.CharField(max_length=40)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'nhw_kalimah_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevelationLocation',
            fields=[
                ('revelation_location_id', models.FloatField(primary_key=True, serialize=False)),
                ('location_seq_no', models.FloatField()),
                ('revelation_location_name', models.CharField(max_length=20)),
                ('create_date', models.DateField()),
                ('create_user', models.CharField(max_length=40)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'revelation_location',
                'ordering': ['location_seq_no'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RootLetter',
            fields=[
                ('root_letter_id', models.FloatField(primary_key=True, serialize=False)),
                ('root_letter_seq_no', models.FloatField()),
                ('root_letter_text', models.CharField(max_length=15, unique=True)),
                ('confirmation_flag', models.FloatField()),
                ('root_letter_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateField()),
                ('create_user', models.CharField(max_length=40)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'root_letter',
                'ordering': ['root_letter_text'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soorah',
            fields=[
                ('soorah_id', models.FloatField(primary_key=True, serialize=False)),
                ('soorah_seq_no', models.FloatField(db_comment='Sequence of Soorah in Quran')),
                ('soorah_name', models.CharField(max_length=80, unique=True)),
                ('create_date', models.DateField()),
                ('create_user', models.CharField(max_length=40)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_user', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'soorah',
                'db_table_comment': 'Names of Quran soorahs',
                'ordering': ['soorah_seq_no'],
                'managed': False,
            },
        ),
    ]
