# Generated by Django 5.0.6 on 2024-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concordanceQuranDRF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwAyatDetailsByRoot',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('kalimah_seq_no', models.FloatField(blank=True, null=True)),
                ('kalimah_text', models.CharField(max_length=100)),
                ('root_letter_id', models.FloatField(blank=True, null=True)),
                ('soorah_seq_no', models.FloatField()),
                ('soorah_seq_no_ar', models.CharField(max_length=10)),
                ('soorah_name', models.CharField(max_length=80)),
                ('ayat_seq_no', models.FloatField()),
                ('ayat_seq_no_ar', models.CharField(max_length=10)),
                ('ayat_text', models.CharField(max_length=2500)),
                ('translation_urdu', models.CharField(blank=True, max_length=2900, null=True)),
                ('translation_english', models.CharField(blank=True, max_length=2900, null=True)),
                ('revelation_location_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vw_ayat_details_by_root',
                'ordering': ['kalimah_seq_no', 'kalimah_text', 'soorah_seq_no', 'ayat_seq_no'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AyatDetailsByRoot',
        ),
    ]
