# Generated by Django 5.0.6 on 2024-09-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concordanceQuranDRF', '0003_vwrootbyalpha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VwRootByAlpha',
        ),
    ]
